export const cities = [
  {
    label: 'Aluthgama',
    value: 'Aluthgama',
    suburbs: [
      {label: 'Adhikarigoda', value: 'Adhikarigoda'},
      {label: 'Alakadupitiya', value: 'Alakadupitiya'},
      {label: 'Aluthgama', value: 'Aluthgama'},
      {label: 'Angagoda', value: 'Angagoda'},
      {label: 'Bentota', value: 'Bentota'},
      {label: 'Bodhimaluwa', value: 'Bodhimaluwa'},
      {label: 'Dedduwa', value: 'Dedduwa'},
      {label: 'Dharga Town', value: 'Dharga Town'},
      {label: 'Galhena', value: 'Galhena'},
      {label: 'Ganegama', value: 'Ganegama'},
      {label: 'Kadiyawatta', value: 'Kadiyawatta'},
    ],
  },
  {
    label: 'Ambalangoda',
    value: 'Ambalangoda',
    suburbs: [
      {label: 'Ambalangoda', value: 'Ambalangoda'},
      {label: 'Andadola', value: 'Andadola'},
      {label: 'Balapitiya', value: 'Balapitiya'},
      {label: 'Delduwa', value: 'Delduwa'},
      {label: 'Dewagoda', value: 'Dewagoda'},
      {label: 'Godahena', value: 'Godahena'},
      {label: 'Heenahatiya', value: 'Heenahatiya'},
      {label: 'Hirewatta', value: 'Hirewatta'},
      {label: 'Kaluwadumulla', value: 'Kaluwadumulla'},
      {label: 'Kuleegoda', value: 'Kuleegoda'},
      {label: 'Petiwatta', value: 'Petiwatta'},
    ],
  },
  {
    label: 'Bandaragama',
    value: 'Bandaragama',
    suburbs: [
      {label: 'Atulugama', value: 'Atulugama'},
      {label: 'Bamunumulla', value: 'Bamunumulla'},
      {label: 'Bandaragama', value: 'Bandaragama'},
      {label: 'Delkada - Bandaragama', value: 'Delkada - Bandaragama'},
      {label: 'Epitamulla - Bandaragama', value: 'Epitamulla - Bandaragama'},
      {label: 'Galgemandiya', value: 'Galgemandiya'},
      {label: 'Gelanigama', value: 'Gelanigama'},
    ],
  },
  {
    label: 'Chilaw',
    value: 'Chilaw',
    suburbs: [
      {label: 'Aluthwatta', value: 'Aluthwatta'},
      {label: 'Bangadeniya', value: 'Bangadeniya'},
      {label: 'Chilaw', value: 'Chilaw'},
      {label: 'Deduruoya', value: 'Deduruoya'},
      {label: 'Ichchampitiya', value: 'Ichchampitiya'},
      {label: 'Kurusapaduwa', value: 'Kurusapaduwa'},
      {label: 'Melpura', value: 'Melpura'},
    ],
  },
  {
    label: 'Colombo',
    value: 'Colombo',
    suburbs: [
      {label: 'Aluthmawatha', value: 'Aluthmawatha'},
      {label: 'Bambalapitiya', value: 'Bambalapitiya'},
      {label: 'Cinammon Gardens', value: 'Cinammon Gardens'},
      {label: 'Colombo 1', value: 'Colombo 1'},
      {label: 'Colombo 10', value: 'Colombo 10'},
      {label: 'Colombo 11', value: 'Colombo 11'},
      {label: 'Colombo 12', value: 'Colombo 12'},
      {label: 'Colombo 13', value: 'Colombo 13'},
      {label: 'Colombo 14', value: 'Colombo 14'},
    ],
  },
  {
    label: 'Galle',
    value: 'Galle',
    suburbs: [
      {label: 'Abeysundarawatta', value: 'Abeysundarawatta'},
      {label: 'Batadoowa', value: 'Batadoowa'},
      {label: 'Batagamvila', value: 'Batagamvila'},
      {label: 'Boossa', value: 'Boossa'},
      {label: 'Dadalla', value: 'Dadalla'},
      {label: 'Dangedara', value: 'Dangedara'},
      {label: 'Ettiligoda', value: 'Ettiligoda'},
      {label: 'Galle Fort', value: 'Galle Fort'},
      {label: 'Kalegana', value: 'Kalegana'},
    ],
  },
];
